/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CockpitSunitaRouteImport } from './routes/cockpit.sunita'
import { Route as CockpitRohitRouteImport } from './routes/cockpit.rohit'
import { Route as CockpitPriyaRouteImport } from './routes/cockpit.priya'
import { Route as CockpitAnupamRouteImport } from './routes/cockpit.anupam'
import { Route as CockpitAaravRouteImport } from './routes/cockpit.aarav'
import { Route as CockpitPersonaSectionRouteImport } from './routes/cockpit.$persona.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitSunitaRoute = CockpitSunitaRouteImport.update({
  id: '/cockpit/sunita',
  path: '/cockpit/sunita',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitRohitRoute = CockpitRohitRouteImport.update({
  id: '/cockpit/rohit',
  path: '/cockpit/rohit',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitPriyaRoute = CockpitPriyaRouteImport.update({
  id: '/cockpit/priya',
  path: '/cockpit/priya',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitAnupamRoute = CockpitAnupamRouteImport.update({
  id: '/cockpit/anupam',
  path: '/cockpit/anupam',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitAaravRoute = CockpitAaravRouteImport.update({
  id: '/cockpit/aarav',
  path: '/cockpit/aarav',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitPersonaSectionRoute = CockpitPersonaSectionRouteImport.update({
  id: '/cockpit/$persona/$section',
  path: '/cockpit/$persona/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cockpit/aarav': typeof CockpitAaravRoute
  '/cockpit/anupam': typeof CockpitAnupamRoute
  '/cockpit/priya': typeof CockpitPriyaRoute
  '/cockpit/rohit': typeof CockpitRohitRoute
  '/cockpit/sunita': typeof CockpitSunitaRoute
  '/cockpit/$persona/$section': typeof CockpitPersonaSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cockpit/aarav': typeof CockpitAaravRoute
  '/cockpit/anupam': typeof CockpitAnupamRoute
  '/cockpit/priya': typeof CockpitPriyaRoute
  '/cockpit/rohit': typeof CockpitRohitRoute
  '/cockpit/sunita': typeof CockpitSunitaRoute
  '/cockpit/$persona/$section': typeof CockpitPersonaSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cockpit/aarav': typeof CockpitAaravRoute
  '/cockpit/anupam': typeof CockpitAnupamRoute
  '/cockpit/priya': typeof CockpitPriyaRoute
  '/cockpit/rohit': typeof CockpitRohitRoute
  '/cockpit/sunita': typeof CockpitSunitaRoute
  '/cockpit/$persona/$section': typeof CockpitPersonaSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cockpit/aarav'
    | '/cockpit/anupam'
    | '/cockpit/priya'
    | '/cockpit/rohit'
    | '/cockpit/sunita'
    | '/cockpit/$persona/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cockpit/aarav'
    | '/cockpit/anupam'
    | '/cockpit/priya'
    | '/cockpit/rohit'
    | '/cockpit/sunita'
    | '/cockpit/$persona/$section'
  id:
    | '__root__'
    | '/'
    | '/cockpit/aarav'
    | '/cockpit/anupam'
    | '/cockpit/priya'
    | '/cockpit/rohit'
    | '/cockpit/sunita'
    | '/cockpit/$persona/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CockpitAaravRoute: typeof CockpitAaravRoute
  CockpitAnupamRoute: typeof CockpitAnupamRoute
  CockpitPriyaRoute: typeof CockpitPriyaRoute
  CockpitRohitRoute: typeof CockpitRohitRoute
  CockpitSunitaRoute: typeof CockpitSunitaRoute
  CockpitPersonaSectionRoute: typeof CockpitPersonaSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit/sunita': {
      id: '/cockpit/sunita'
      path: '/cockpit/sunita'
      fullPath: '/cockpit/sunita'
      preLoaderRoute: typeof CockpitSunitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit/rohit': {
      id: '/cockpit/rohit'
      path: '/cockpit/rohit'
      fullPath: '/cockpit/rohit'
      preLoaderRoute: typeof CockpitRohitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit/priya': {
      id: '/cockpit/priya'
      path: '/cockpit/priya'
      fullPath: '/cockpit/priya'
      preLoaderRoute: typeof CockpitPriyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit/anupam': {
      id: '/cockpit/anupam'
      path: '/cockpit/anupam'
      fullPath: '/cockpit/anupam'
      preLoaderRoute: typeof CockpitAnupamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit/aarav': {
      id: '/cockpit/aarav'
      path: '/cockpit/aarav'
      fullPath: '/cockpit/aarav'
      preLoaderRoute: typeof CockpitAaravRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit/$persona/$section': {
      id: '/cockpit/$persona/$section'
      path: '/cockpit/$persona/$section'
      fullPath: '/cockpit/$persona/$section'
      preLoaderRoute: typeof CockpitPersonaSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CockpitAaravRoute: CockpitAaravRoute,
  CockpitAnupamRoute: CockpitAnupamRoute,
  CockpitPriyaRoute: CockpitPriyaRoute,
  CockpitRohitRoute: CockpitRohitRoute,
  CockpitSunitaRoute: CockpitSunitaRoute,
  CockpitPersonaSectionRoute: CockpitPersonaSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
